# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicants', '0002_auto_20151224_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='github_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(blank=True, help_text="When an Applicant is given a user account, that basically means they've been accepted into 3SC", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
