# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_auto_20151224_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
